# List all available recipes
default:
    @just --list

# Compile Tailwind css, then build the site with Zola
build: tailwind-build
    zola build

# Try to build site without rendering (checks links)
check:
    zola check

# Clear public directory generated by Zola
reset:
    rm -rf public

# Install Node.js dependencies
install:
    npm install

# Move basecoat component js files from node_modules to static/js
basecoat:
    #!/usr/bin/env bash
    cp node_modules/basecoat-css/dist/js/*.js static/js/
    echo "Successfully copied basecoat component js to static/js"

# Render a single qmd file at content/{{path}}
render path:
	#!/usr/bin/env bash
	set -euo pipefail
	src='{{path}}'
	src="${src#content/}"
	if [[ "$src" == blog/* ]]; then
		echo "render: found 'blog/' path, use 'just render-post'" >&2
		exit 1
	fi
	# move to content folder so _quarto.yml is invoked
	cd content
	# clear .md file to prevent quarto from writing to another file
	rm -f "${src%.qmd}.md"
	quarto render "$src" -M engine:knitr


# Render all qmd files in content/{{path}}/ non-recursively (fails if path="blog/")
render-dir path:
	#!/usr/bin/env bash
	set -euo pipefail
	target='{{path}}'
	target="${target#content/}"
	target="${target%/}"
	if [ "$target" = "blog" ]; then
		echo "render-dir: found 'blog/' path, use 'just render-post' instead" >&2
		exit 1
	fi
	cd content
	shopt -s nullglob
	files=( "$target"/*.qmd )
	if [ ${#files[@]} -eq 0 ]; then
		echo "No .qmd files found under content/$target" >&2
		exit 1
	fi
	for src in "${files[@]}"; do
		rm -f "${src%.qmd}.md"
		base=$(basename "$src")
		dir=$(dirname "$src")
		tmp_src="$dir/x${base}"
		mv "$src" "$tmp_src"
		trap 'mv "$tmp_src" "$src" 2>/dev/null' EXIT
		quarto render "$tmp_src" -M engine:knitr
		mv "${tmp_src%.qmd}.md" "${src%.qmd}.md"
		mv "$tmp_src" "$src"
		trap - EXIT
	done

# Render all qmd files in content/ (except those in "blog/")
render-all:
	#!/usr/bin/env bash
	set -euo pipefail
	cd content
	shopt -s globstar nullglob
	files=()
	for f in **/*.qmd; do
		[[ "$f" == blog/* ]] && continue
		files+=( "$f" )
	done
	if [ ${#files[@]} -eq 0 ]; then
		echo "No .qmd files to render" >&2
		exit 1
	fi
	for src in "${files[@]}"; do
		rm -f "${src%.qmd}.md"
		base=$(basename "$src")
		dir=$(dirname "$src")
		tmp_src="$dir/x${base}"
		mv "$src" "$tmp_src"
		trap 'mv "$tmp_src" "$src" 2>/dev/null' EXIT
		quarto render "$tmp_src" -M engine:knitr
		mv "${tmp_src%.qmd}.md" "${src%.qmd}.md"
		mv "$tmp_src" "$src"
		trap - EXIT
	done

# Generate Tailwind static/style.css from css/style.css
tailwind-build:
    npm run tailwind:build

# Create a new documentation page at content/{{path}}
new-page path:
	#!/usr/bin/env bash
	set -euo pipefail
	rel='{{path}}'
	rel="${rel#content/}"
	if [[ "$rel" == blog/* ]]; then
		echo "new-page: found 'blog/' path, use 'just new-post' instead" >&2
		exit 1
	fi
	file="content/$rel"
	parent=$(dirname "$file")
	if [ ! -d "$parent" ]; then
		echo "new-page: section $parent does not exist, use 'just new-section' first" >&2
		exit 1
	fi
	if [ -e "$file" ]; then
		echo "File exists: $file" >&2
		exit 1
	fi
	cat > "$file" <<-EOF
	---
	title:
	description: ""
	weight: 0
	extra:
	  short_title:
	---
	EOF
	echo "Created $file"

# Create a new documentation section at content/{{path}}/
new-section path:
	#!/usr/bin/env bash
	set -euo pipefail
	dir="content/{{path}}"
	dir="${dir%/}"
	file="$dir/_index.qmd"
	if [ -e "$file" ]; then
		echo "File exists: $file" >&2
		exit 1
	fi
	mkdir -p "$dir"
	cat > "$file" <<-EOF
	---
	title:
	description: ""
	weight: 0
	extra:
	  section_title:
	---
	EOF
	echo "Created $file"

# Create a new blog post at content/blog/{{date}}-{{title}}/index.qmd
new-post title:
	#!/usr/bin/env bash
	set -euo pipefail
	date=$(date +%Y-%m-%d)
	dir="content/posts/${date}-{{title}}"
	mkdir -p "$dir"
	cat > "$dir/index.qmd" <<-EOF
	---
	title: {{title}}
	date: "$date"
	authors: []
	taxonomies:
	  tags: []
	---
	EOF
	echo "Created $dir/index.qmd"

# Render a blog post at content/blog/{{date}}-{{title}}/index.qmd
render-post title:
    #!/usr/bin/env bash
    set -euo pipefail
    shopt -s nullglob
    matches=( content/blog/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]-{{title}} )
    if [ ${#matches[@]} -eq 0 ]; then
        echo "No post found matching *-{{title}}" >&2; exit 1
    elif [ ${#matches[@]} -gt 1 ]; then
        echo "Ambiguous title, matched: ${matches[*]}" >&2; exit 1
    fi
    quarto render "${matches[0]}/index.qmd" -M engine:knitr

# Run Tailwind watch and Zola live serve in parallel
dev: 
	npm run dev
