# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib examples, .registration = TRUE
NULL

#' @export
test_hm_i32 <- function(x) .Call(wrap__test_hm_i32, x)

#' @export
test_hm_string <- function(x) .Call(wrap__test_hm_string, x)

#' @export
test_hm_custom_try_from <- function(x) .Call(wrap__test_hm_custom_try_from, x)

#' @export
check_default <- function(x = NULL) .Call(wrap__check_default, x)

#' @export
greet <- function(name, loud = FALSE) .Call(wrap__greet, name, loud)

#' @export
multiply <- function(x, multiplier = 1.0, round_result = FALSE) .Call(wrap__multiply, x, multiplier, round_result)

#' @export
create_person <- function() .Call(wrap__create_person)

#' @export
run_analysis <- function() .Call(wrap__run_analysis)

#' @export
get_config <- function() .Call(wrap__get_config)

#' @export
point_from_r <- function(x) .Call(wrap__point_from_r, x)

#' @export
round_trip <- function(x) .Call(wrap__round_trip, x)

#' @export
replicate_point <- function(x, n) .Call(wrap__replicate_point, x, n)

#' @export
make_multipoint <- function(x) .Call(wrap__make_multipoint, x)

#' @export
centroid <- function(x) .Call(wrap__centroid, x)

#' @export
Shape <- new.env(parent = emptyenv())

Shape$new <- function(x) .Call(wrap__Shape__new, x)

Shape$n_coords <- function() .Call(wrap__Shape__n_coords, self)

#' @rdname Shape
#' @usage NULL
#' @export
`$.Shape` <- function (self, name) { func <- Shape[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Shape` <- `$.Shape`

#' @export
#' @export
Wrapper <- new.env(parent = emptyenv())

Wrapper$new <- function(x) .Call(wrap__Wrapper__new, x)

Wrapper$value <- function() .Call(wrap__Wrapper__value, self)

#' @rdname Wrapper
#' @usage NULL
#' @export
`$.Wrapper` <- function (self, name) { func <- Wrapper[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Wrapper` <- `$.Wrapper`

#' @export
#' @export
#' @section Methods:
#'\subsection{Method `new`}{
#'Create a new Counter starting at zero.
#' \subsection{return}{
#'A `Counter` object.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `increment`}{
#'Increment the counter by one.
#' \subsection{return}{
#'Self (invisibly)
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `value`}{
#'Return the current count.
#' \subsection{return}{
#'An integer.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
Counter <- new.env(parent = emptyenv())

Counter$new <- function() .Call(wrap__Counter__new)

Counter$increment <- function() .Call(wrap__Counter__increment, self)

Counter$value <- function() .Call(wrap__Counter__value, self)

#' @rdname Counter
#' @usage NULL
#' @export
`$.Counter` <- function (self, name) { func <- Counter[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Counter` <- `$.Counter`

#' @export
#' @export
StatefulCounter <- new.env(parent = emptyenv())

StatefulCounter$new <- function() .Call(wrap__StatefulCounter__new)

StatefulCounter$increment <- function() .Call(wrap__StatefulCounter__increment, self)

StatefulCounter$get <- function() .Call(wrap__StatefulCounter__get, self)

#' @rdname StatefulCounter
#' @usage NULL
#' @export
`$.StatefulCounter` <- function (self, name) { func <- StatefulCounter[[name]]; environment(func) <- environment(); func }

#' @export
`[[.StatefulCounter` <- `$.StatefulCounter`

# nolint end
