# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib heck, .registration = TRUE
NULL

#' @export
to_snek_case <- function(x) .Call(wrap__to_snek_case, x)

#' @export
to_shouty_snake_case <- function(x) .Call(wrap__to_shouty_snake_case, x)

#' @export
to_kebab_case <- function(x) .Call(wrap__to_kebab_case, x)

#' @export
to_shouty_kebab_case <- function(x) .Call(wrap__to_shouty_kebab_case, x)

#' @export
to_pascal_case <- function(x) .Call(wrap__to_pascal_case, x)

#' @export
to_upper_camel_case <- function(x) .Call(wrap__to_upper_camel_case, x)

#' @export
to_train_case <- function(x) .Call(wrap__to_train_case, x)

#' @export
to_title_case <- function(x) .Call(wrap__to_title_case, x)

# nolint end
